In [1]:
import pandas as pd

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
data = pd.read_excel("iris_train.xlsx")

In [8]:
data.head()

   sepallength  sepalwidth  petallength  petalwidth           class
0          7.2         3.6          6.1         2.5  Iris-virginica
1          6.3         3.3          6.0         2.5  Iris-virginica
2          6.7         3.3          5.7         2.5  Iris-virginica
3          6.3         3.4          5.6         2.4  Iris-virginica
4          6.7         3.1          5.6         2.4  Iris-virginica

In [11]:
x = data.iloc[:,:-1]

In [12]:
x

     sepallength  sepalwidth  petallength  petalwidth
0            7.2         3.6          6.1         2.5
1            6.3         3.3          6.0         2.5
2            6.7         3.3          5.7         2.5
3            6.3         3.4          5.6         2.4
4            6.7         3.1          5.6         2.4
..           ...         ...          ...         ...
122          5.0         3.0          1.6         0.2
123          5.4         3.7          1.5         0.2
124          5.3         3.7          1.5         0.2
125          5.2         3.5          1.5         0.2
126          5.1         3.4          1.5         0.2

[127 rows x 4 columns]

In [13]:
y = data.iloc[:,-1]

In [14]:
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
122       Iris-setosa
123       Iris-setosa
124       Iris-setosa
125       Iris-setosa
126       Iris-setosa
Name: class, Length: 127, dtype: object

In [16]:
model = RandomForestClassifier()

In [17]:
model.fit(x,y)

RandomForestClassifier()

In [18]:
predictions = model.predict([[5.4,3,4.5,1.5]])

C:\Users\rani mahajan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [19]:
predictions

array(['Iris-versicolor'], dtype=object)

In [20]:
x.values

array([[7.2, 3.6, 6.1, 2.5],
       [6.3, 3.3, 6. , 2.5],
       [6.7, 3.3, 5.7, 2.5],
       [6.3, 3.4, 5.6, 2.4],
       [6.7, 3.1, 5.6, 2.4],
       [5.8, 2.8, 5.1, 2.4],
       [7.7, 2.6, 6.9, 2.3],
       [7.7, 3. , 6.1, 2.3],
       [6.8, 3.2, 5.9, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [6.2, 3.4, 5.4, 2.3],
       [6.4, 3.2, 5.3, 2.3],
       [6.7, 3. , 5.2, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [6.5, 3. , 5.8, 2.2],
       [6.4, 2.8, 5.6, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [7.1, 3. , 5.9, 2.1],
       [6.7, 3.3, 5.7, 2.1],
       [6.4, 2.8, 5.6, 2.1],
       [6.8, 3. , 5.5, 2.1],
       [6.9, 3.1, 5.4, 2.1],
       [7.7, 2.8, 6.7, 2. ],
       [7.9, 3.8, 6.4, 2. ],
       [6.5, 3. , 5.2, 2. ],
       [6.5, 3.2, 5.1, 2. ],
       [5.7, 2.5, 5. , 2. ],
       [5.6, 2.8, 4.9, 2. ],
       [7.4, 2.8, 6.1, 1.9],
       [6.4, 2.7, 5.3, 1.9],
       [5.8, 2.7, 5.1, 1.9],
       [5.8, 2.7, 5.1, 1.9],
       [6.3, 2.5, 5. , 1.9],
       [7.3, 2.9, 6.3, 1.8],
       [7.2, 3.2, 6. , 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [6.3, 2.9, 5.6, 1.8],
       [6.4, 3.1, 5.5, 1.8],
       [6.5, 3. , 5.5, 1.8],
       [5.9, 3. , 5.1, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.3, 2.7, 4.9, 1.8],
       [5.9, 3.2, 4.8, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.7, 3. , 5. , 1.7],
       [4.9, 2.5, 4.5, 1.7],
       [7.2, 3. , 5.8, 1.6],
       [6. , 2.7, 5.1, 1.6],
       [6.3, 3.3, 4.7, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6.3, 2.8, 5.1, 1.5],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.3, 2.5, 4.9, 1.5],
       [6.7, 3.1, 4.7, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [5.6, 3. , 4.5, 1.5],
       [5.4, 3. , 4.5, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [6.2, 2.2, 4.5, 1.5],
       [5.9, 3. , 4.2, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [7. , 3.2, 4.7, 1.4],
       [6.1, 2.9, 4.7, 1.4],
       [6.1, 3. , 4.6, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [6.6, 3. , 4.4, 1.4],
       [5.2, 2.7, 3.9, 1.4],
       [6.6, 2.9, 4.6, 1.3],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 2.3, 4.4, 1.3],
       [6.4, 2.9, 4.3, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.9, 4.2, 1.3],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [6.1, 2.8, 4. , 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.3, 4. , 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [6.1, 2.8, 4.7, 1.2],
       [5.5, 2.6, 4.4, 1.2],
       [5.7, 3. , 4.2, 1.2],
       [5.8, 2.6, 4. , 1.2],
       [5.8, 2.7, 3.9, 1.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.5, 2.4, 3.8, 1.1],
       [5.1, 2.5, 3. , 1.1],
       [5.8, 2.7, 4.1, 1. ],
       [6. , 2.2, 4. , 1. ],
       [5.5, 2.4, 3.7, 1. ],
       [5.7, 2.6, 3.5, 1. ],
       [5. , 2. , 3.5, 1. ],
       [4.9, 2.4, 3.3, 1. ],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.3, 1.7, 0.5],
       [5.1, 3.8, 1.9, 0.4],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 3.4, 1.6, 0.4],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 3.7, 1.5, 0.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.1, 3.5, 1.4, 0.3],
       [4.6, 3.4, 1.4, 0.3],
       [4.8, 3. , 1.4, 0.3],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.8, 3.4, 1.9, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [5.1, 3.4, 1.5, 0.2]])

In [21]:
data = pd.read_excel("iris_test.xlsx")

In [26]:
x_test = data.iloc[:,:-1]

In [27]:
x_test

    sepallength  sepalwidth  petallength  petalwidth
0           5.0         3.4          1.5         0.2
1           4.6         3.1          1.5         0.2
2           5.5         4.2          1.4         0.2
3           5.0         3.6          1.4         0.2
4           5.1         3.5          1.4         0.2
5           5.2         3.4          1.4         0.2
6           5.0         3.3          1.4         0.2
7           4.6         3.2          1.4         0.2
8           4.9         3.0          1.4         0.2
9           4.4         2.9          1.4         0.2
10          5.5         3.5          1.3         0.2
11          4.7         3.2          1.3         0.2
12          4.4         3.2          1.3         0.2
13          4.4         3.0          1.3         0.2
14          5.8         4.0          1.2         0.2
15          5.0         3.2          1.2         0.2
16          4.6         3.6          1.0         0.2
17          5.2         4.1          1.5         0.1
18          4.9         3.1          1.5         0.1
19          4.9         3.1          1.5         0.1
20          4.9         3.1          1.5         0.1
21          4.8         3.0          1.4         0.1
22          4.3         3.0          1.1         0.1

In [28]:
y_test = data.iloc[:,-1]

In [29]:
y_test

0     Iris-setosa
1     Iris-setosa
2     Iris-setosa
3     Iris-setosa
4     Iris-setosa
5     Iris-setosa
6     Iris-setosa
7     Iris-setosa
8     Iris-setosa
9     Iris-setosa
10    Iris-setosa
11    Iris-setosa
12    Iris-setosa
13    Iris-setosa
14    Iris-setosa
15    Iris-setosa
16    Iris-setosa
17    Iris-setosa
18    Iris-setosa
19    Iris-setosa
20    Iris-setosa
21    Iris-setosa
22    Iris-setosa
Name: class, dtype: object

In [30]:
predictions = model.predict(x_test.values)

C:\Users\rani mahajan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [31]:
predictions

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa'], dtype=object)